import { db } from '@/config/db';
import { coursesTable } from '@/config/schema';

import { currentUser } from '@clerk/nextjs/server';
import {
  GoogleGenAI,
} from '@google/genai';

import { NextResponse } from 'next/server';

// Helper function to generate course image
const generateCourseImage = async (topic, category) => {
  try {
    const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000';
    const response = await fetch(`${baseUrl}/api/generate-course-image`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ topic, category })
    });

    if (response.ok) {
      const imageData = await response.json();
      return imageData.imageUrl;
    }
  } catch (error) {
    console.error('Error generating course image:', error);
  }
  
  // Fallback image
  return "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=1200&h=600&fit=crop";
};


const PROMPT =`Genrate Learning Course depends on following details. In which Make sure to add Course Name, Description,Course Banner Image Prompt (Create a modern, flat-style 2D digital illustration representing user Topic. Include UI/UX elements such as mockup screens, text blocks, icons, buttons, and creative workspace tools. Add symbolic elements related to user Course, like sticky notes, design components, and visual aids. Use a vibrant color palette (blues, purples, oranges) with a clean, professional look. The illustration should feel creative, tech-savvy, and educational, ideal for visualizing concepts in user Course) for Course Banner in 3d format Chapter Name, , Topic under each chapters , Duration for each chapters etc, in JSON format only

Schema:

{
  "course": {
    "name": "string",
    "description": "string",
    "category": "string",
    "level": "string",
    "includeVideo": "boolean",
    "noOfChapters": "number",

"bannerImagePrompt": "string",
    "chapters": [
      {
        "chapterName": "string",
        "duration": "string",
        "topics": [
          "string"
        ],
     
      }
    ]
  }
}

, User Input: 

 
`
;


  export const ai = new GoogleGenAI({
    apiKey: process.env.GEMINI_API_KEY,
  });



export async function POST(request) {
    const {courseId, ...formData} = await request.json();
    const user= await currentUser();
    
    // Check subscription limit before creating course
    if (user?.primaryEmailAddress?.emailAddress) {
        const { checkSubscriptionLimit } = await import('@/lib/subscription');
        const limitCheck = await checkSubscriptionLimit(user.primaryEmailAddress.emailAddress, 'course');
        
        if (!limitCheck.allowed) {
            return NextResponse.json(
                { error: limitCheck.reason, limit: limitCheck.limit },
                { status: 403 }
            );
        }
    }

  const config = {
    responseMimeType: 'text/plain',
  };
  const model = 'gemini-2.5-flash';
  const contents = [
    {
      role: 'user',
      parts: [
        {
          text: PROMPT+JSON.stringify(formData),
        },
      ],
    },
  ];

  const response = await ai.models.generateContent({
    model,
    config,
    contents,
  });
  console.log(response.candidates[0].content.parts[0].text);
  const RawResp= response?.candidates[0]?.content?.parts[0]?.text;
  const RawJson=RawResp.replace('```json','').replace('```','');
  const JSONResp= JSON.parse(RawJson);

  // Generate dynamic course image based on topic and category
  const courseImage = await generateCourseImage(
    formData.name || formData.topic || 'education',
    formData.category || 'learning'
  );
  console.log('Generated course image:', courseImage);
 
// save response to database generated by ai 

const  result = await db.insert(coursesTable).values({
    ...formData,
    courseJson: JSONResp,
    courseImage: courseImage, // Add the dynamic image URL
    userEmail:user?.primaryEmailAddress?.emailAddress,
    cid: courseId,
});

  return NextResponse.json({courseId:courseId, courseImage: courseImage });
}

// const GenerateImage = async (ImagePrompt) => {
//   const BASE_URL='https://aigurulab.tech';
// const result = await axios.post(BASE_URL+'/api/generate-image',
//         {
//             width: 1024,
//             height: 1024,
//             input: "self-portrait of a woman, lightning in the background",
//             model: 'sdxl',//'flux'
//             aspectRatio:"16:9"//Applicable to Flux model only
//         },
//         {
//             headers: {
//                 'x-api-key': apiKey, // Your API Key
//                 'Content-Type': 'application/json', // Content Type
//             },
//         })
// console.log(result.data.image) //Output Result: Base 64 Image
// }
